### ISSUE TITLE
Rider auto-generate run-configurations (Start/Debug/Profile Godot Editor)

### ISSUE THREAD

**Issue by van800** [JetBrains/godot-support#1]
moved from https://youtrack.jetbrains.com/issue/RIDER-38108

**Comment by van800** [comment]
Action button for Profiling:
![image](https://user-images.githubusercontent.com/1482681/75788117-0def7400-5d68-11ea-999d-cb8f1840b7d1.png)

**Comment by van800** [comment]
Further improvement depends on https://github.com/godotengine/godot-proposals/issues/555

**Comment by Meister1593** [comment]
+1

**Comment by van800** [comment]
Last thing missing are configurations for Debug/Profile Editor.

**Comment by abueide** [comment]
@van800 is there currently any way to run a godot game using rider's profiling features?

**Comment by van800** [comment]
Yes, see
https://github.com/JetBrains/godot-support/issues/1#issuecomment-593994688

**Comment by abueide** [comment]
@van800 oh mb I didn't see the PR

**Comment by van800** [comment]
fixed in plugin .36, which targets 2020.2 EAP5+
