### ISSUE TITLE
Output of "Start with debug" is disabled or not working

### ISSUE THREAD

**Issue by Meister1593** [JetBrains/godot-support#10]
I can't see output of console while running through this button, like `GD.Print()` stuff and etc which outputs to console.
*old way is to run `Listen(1)` and `Run with attach (2)` run configurations which allows to run game with debugging without Godot buttons.
Running old way:
![image](https://user-images.githubusercontent.com/7141787/78929823-1d26b780-7ab4-11ea-959d-72468ea38c44.png)
Running with new button:
![image](https://user-images.githubusercontent.com/7141787/78929919-421b2a80-7ab4-11ea-8cac-5ea895c4a073.png)
![image](https://user-images.githubusercontent.com/7141787/78929930-45aeb180-7ab4-11ea-9765-c2a597edb86a.png)

Using Godot 3.2.1 (Mono), Godot Support 2020.1.3, Rider 2020.1 EAP 7 on Arch Linux

**Comment by Meister1593** [comment]
Restarted Godot fully, now it's working, it opens another terminal window with output (`GD.print and etc from game`) of debugger.
#10 Works so far

**Comment by hhyyrylainen** [comment]
So is it now intended behaviour that when debugging a new terminal window opens with the game output? This is not very usable as, as soon as the game closes the output is lost.

**Comment by van800** [comment]
@hhyyrylainen please add a new issue and mention this one. Thanks!
