### ISSUE TITLE
Suddenly stopped working, closing after opening project selector

### ISSUE THREAD

**Issue by gosferano** [JetBrains/godot-support#100]
Hello

Was happily using it until today when it stopped working as expected. Now after running either Player or Editor configuration I get prompted with Godot's project selection window and after double clicking my project it just exits with code 0.

Any fixed, workarounds, ideas why it might be the way it is?

Kind regards

**Comment by van800** [comment]
Try to remove configurations and close open solution. I expect them to be recreated.
