### ISSUE TITLE
Cannot debug the plugin in Rider

### ISSUE THREAD

**Issue by jsbeckr** [JetBrains/godot-support#101]
I'm trying to integrate https://github.com/godotengine/godot/tree/master/modules/mono/editor/GodotTools/GodotTools.IdeMessaging to get NodePath, Input and other completions to work with Rider. 

The problem is that I cannot debug the plugin while it is running in the sandbox, which makes the whole process quite annoying. I use the `runIde` run configuration. Should that work out of the box or is there a trick that I don't know?

**Comment by van800** [comment]
Maybe you are opening wrong folder in IDEA.
<img width="612" alt="image" src="https://github.com/JetBrains/godot-support/assets/1482681/1a427265-1f73-42fb-a0b8-4d4acf668924">
You may see, that I have a regular "debug" command near the run-configuration.

**Comment by jsbeckr** [comment]
Yes in IDEA I can debug and break in the Kotlin code. But I wanted to debug my C# code.

**Comment by jsbeckr** [comment]
Ah okay I was a bit dumb. Of course I can just attach the debugger in Rider. Works now!
