### ISSUE TITLE
.NET Eexcutable instead of Godot Start and Debug

### ISSUE THREAD

**Issue by Perndoe** [JetBrains/godot-support#105]
The plugin automatically use .NET Executable when making a new project.

![image](https://github.com/JetBrains/godot-support/assets/81963564/d97df9d4-5256-4144-a2c0-c398cf71d9ab)

**Comment by van800** [comment]
I think for the Godot 4 it is correct approach. What is the issue here? What version of the Godot support plugin do you have?

**Comment by Perndoe** [comment]
> I think for the Godot 4 it is correct approach. What is the issue here? What version of the Godot support plugin do you have?

I got the latest one for stable build and the issue is the ide is using .net executable rather than using Godot start and debug

**Comment by van800** [comment]
Special Godot run configuration was a thing only for Godot 3.5.

**Comment by van800** [comment]
If it causes any specific trouble, I mean, some feature doesn't work, please let me know.
