### ISSUE TITLE
Make errors in console output clickable

### ISSUE THREAD

**Issue by geowarin** [JetBrains/godot-support#107]
When launching the game via Godot and an error happens, we get a clean output and the error is clickable (meaning it will open the external editor on the appropriate line)

![image](https://github.com/JetBrains/godot-support/assets/1045636/3a0cdd69-e16d-40a9-88e0-a1bc77a1ac14)

However, when launching the game in Rider, the output is not as clean and, more importantly, not clickable

![image](https://github.com/JetBrains/godot-support/assets/1045636/d6619e40-05a4-48f3-9f65-b103a3dd0dfa)

I think it's because the error reads `.../Script.cs:line 30` instead of `.../Script.cs:30`.

Do you think we should open a PR in godot or we could clean the log directly in the plugin ?

**Comment by van800** [comment]
The format is not an issue here.
Please vote for https://youtrack.jetbrains.com/issue/RIDER-5594/Stack-traces-in-Run-or-Debug-windows-arent-clickable
