### ISSUE TITLE
Godot 4.1 player profiling session stuck starting

### ISSUE THREAD

**Issue by andypandy47** [JetBrains/godot-support#108]
Hi there,

I'm trying out Rider with Godot v4.1 stable mono as I was interested to see what the profiling functionality was like. I've followed the steps outline here https://github.com/godotengine/godot/pull/34382 and I can run my project through the Godot player with the "Profile with Timeline (Mono)" option. However, the profiling session remains stuck trying to start the session (see image below)

<img width="388" alt="image" src="https://github.com/JetBrains/godot-support/assets/19389664/2f3bf94a-76c3-4e3a-bc9c-7c459de0d310">

Any advice on what I'm doing wrong here? This is my player configuration

<img width="555" alt="image" src="https://github.com/JetBrains/godot-support/assets/19389664/e1fb1598-1095-437c-be7b-246a20ddf5b6">

 I've also tried adding the following `MONO_ENV_OPTIONS` into the environment variables but nothing changes
`MONO_ENV_OPTIONS=--profile=jb:prof=timeline,ctl=remote,host=127.0.0.1:55467`

**Comment by van800** [comment]
Godot v4.1 is a dotnetcore not mono. I will take a look, maybe we are confusing stuff.

**Comment by andypandy47** [comment]
Ah I see, I've managed to get some profiling info out of the .Net executable runtime configs. Although so much of the info returned is polluted with calls to `InvokeGodotClassMethod`. You have to drill down quite a bit sometimes depending on the node type. Perhaps this is normal though? Also is strange to see how much time is taken up by the engine doing `StringName` comparisons

<img width="876" alt="image" src="https://github.com/JetBrains/godot-support/assets/19389664/6217fbbe-6ff5-4420-869d-1402ec21b15e">

**Comment by van800** [comment]
You can mark that whole engine assembly/assemblies as System and it would get filtered out.

**Comment by andypandy47** [comment]
Thats so much better, thanks!

**Comment by van800** [comment]
https://github.com/godotengine/godot/pull/34382 updated for Godot 4.
