### ISSUE TITLE
Rider doesn't detect the project as Godot and load the libraries, references etc.

### ISSUE THREAD

**Issue by NibblyPig** [JetBrains/godot-support#111]
There's zero documentation on how to get Godot to work with the Rider that I've been able to find.

I've installed this plugin, and in Godot I've gone to Editor > Editor Settings and under Dotnet > Editor set the external editor to Rider.

Double clicking the .cs file opens the file in Rider.

However there is no integration that I can see. There is no intellisense, Rider doesn't respect any breakpoints or other types of debugging.

According to one tutorial I found, it mentioned that Rider would detect that the project is Godot and you'd be prompted. However this never happened to me.

Everything is up to date, the latest Rider, the latest plugin, and the latest (stable) version of mono godot.

I've tried using the double click approach within Godot and also opening the godot project folder directly in Rider.

Please can you publish some instructions on how to use Godot with Rider, using this plugin.

**Comment by geowarin** [comment]
Godot must generate the sln file for rider to detect the project as a c# project.
You can generate the sln file from godot in the tool menu.

**Comment by NibblyPig** [comment]
Thanks, I tried that, the .sln was visible within Rider but it didn't seem to make any difference. Double clicking the sln opened it in the editor as text. I'll have another play around.

**Comment by van800** [comment]
I can take a look at the logs for some clue. Please either attach here from Help - Collect logs or report privately with Help-Report a Bug, agree to attach logs.

**Comment by NibblyPig** [comment]
I've managed to get it working now, I *think* the problem was that I originally opened the godot project by opening the folder, not the .sln file.  Right clicking the .sln file and choosing open seems to have fixed it.

I wouldn't have expected a difference, given that there aren't now two entries in the 'recent projects' list when opening Rider, so it seems Rider itself doesn't distinguish. Perhaps the Godot project detection is just very specific.

Either way thanks for your help it is working now.

**Comment by van800** [comment]
Do you remember how that happened, that you opened folder instead of the sln?
As far as I know it is common to checkin sln file in the repository. In that case Rider should have asked you to open sln or explicitly open folder. If the project repo is public, I can try myself.

**Comment by van800** [comment]
In a general case, when folder is opened, it is hard to tell that it is a root of Godot solution.
The file "project.godot" might easily be somewhere deeper in the folder structure.
Like in this example https://github.com/van800/godot-demo-projects/tree/net6/mono/dodge_the_creeps
