### ISSUE TITLE
Add "Collapse Duplicate Messages" to Console

### ISSUE THREAD

**Issue by nascentparadigm** [JetBrains/godot-support#112]
This is a feature request to add support for "Collapsing Duplicate Messages" when running/debugging the application, a feature which can be found in Godot's own Output tab in the editor, Visual Studio Code's Debug Console, Unity's Console, and even Rider's Unity-Console integration.  Apologies if this should be a core feature of Rider, and not this plugin specifically (assuming it's plugin specific since the Unity one is).

Examples of desired output:
<img width="176" alt="Screenshot 2023-09-22 at 8 59 10 PM" src="https://github.com/JetBrains/godot-support/assets/145822325/f0356075-4cdc-4a66-ba7e-55fa4c94adbd">
<img width="194" alt="Screenshot 2023-09-22 at 9 00 36 PM" src="https://github.com/JetBrains/godot-support/assets/145822325/5e1f1a30-2a44-47d9-a57a-52b6af0b4bca">

What I currently get:
<img width="146" alt="Screenshot 2023-09-22 at 9 01 17 PM" src="https://github.com/JetBrains/godot-support/assets/145822325/239dc8b0-e1eb-483d-b4e6-ee3f0002e017">

**Comment by van800** [comment]
Thank you for the report.
It definitely sounds like general purpose feature, not just Godot specific. So I have submitted it to IDEA. https://youtrack.jetbrains.com/issue/IDEA-333219/Add-ability-to-Collapsing-Duplicate-Messages-in-run-debug-console
