### ISSUE TITLE
Support project in nested folder in project discovery

### ISSUE THREAD

**Issue by dotlogix** [JetBrains/godot-support#114]
In godot you can specify a custom path for your solution.
Is it possible to still detect the godot project using some configuration or property in the csproj maybe?

I usually use ..\ as my solution path to seperate the sln from the actual projects I often have additional project references.
So in my case the folder structure would be:
Root
  Game.sln
  Game/Game.csproj
  Game/.godot
  Library/Library.csproj

**Comment by van800** [comment]
Such setup works already.

**Comment by dotlogix** [comment]
For me it doesn't but a newly created standard project with .sln and .csproj in the same folder works fine

**Comment by dotlogix** [comment]
Just tested it again with a new project definetly does not work.

Repo steps:
- Open Godot 4.2-beta
- Create a new Project
- Go to Settings/Dotnet and set the solution path to ../
(If you don't see this option enable AdvancedSettings at the top left of the window)
- Go to Project/Tools/C#/Create Solution
- Open the created sln with Rider + Godot Support

Expected:
The extension detects the Project as a Godot Project and creates the Configurations for you.

Actual:
Nothing happens and no Confgurations are created

**Comment by van800** [comment]
@dotlogix What Rider version do you use?

**Comment by dotlogix** [comment]
@van800
JetBrains Rider 2023.2.2
Godot 4.2.beta1
Plugin 2023.2.121

So all up2date I guess

**Comment by van800** [comment]
I can reproduce that first time opening a new project would not recognize it as godot. If I close and open solution again it becomes recognized. 
Is it the same for you?

**Comment by van800** [comment]
[test.zip](https://github.com/JetBrains/godot-support/files/12999287/test.zip)

**Comment by dotlogix** [comment]
With the current version of the plugin it dosn't work for me with your test project either.
Do I need your commit to test this?

**Comment by van800** [comment]
Plugin with this fix published for Rider 2023.2 (plugin version `2023.2.125`)

**Comment by van800** [comment]
Thank you for reporting @dotlogix

**Comment by dotlogix** [comment]
@van800 it unfortunately does not work if the project is part of a solution folder check this out:
[test.zip](https://github.com/JetBrains/godot-support/files/13016622/test.zip)

**Comment by van800** [comment]
No need for a separate issue. Thank you!

**Comment by van800** [comment]
`2023.2.126` with fix for the solution folder case was just published.

**Comment by dotlogix** [comment]
I can confirm that all of my issues are resolved now thx a lot <3
