### ISSUE TITLE
Catastrophic failure when i try to debug specific scene

### ISSUE THREAD

**Issue by Rice00** [JetBrains/godot-support#117]
When i right click on a .tscn file and click on debug scene
the rider shows below:
Catastrophic failure (exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)) The error code is E_ UNEXPECTED, or 0x8000FFFF
but when i click run the scene,it just work successfully
it appear on my every project,and im not sure if this can reproduce on other PC,so i can't give any further infomation.
here are some pictures:
<img width="731" alt="1" src="https://github.com/JetBrains/godot-support/assets/68637466/88537651-4e72-4f93-8604-be1f1bdb9b1d">
<img width="455" alt="2" src="https://github.com/JetBrains/godot-support/assets/68637466/8dec59c0-97d4-44b4-af91-7070b6e4cb1f">
Thank u!

**Comment by van800** [comment]
Would it be possible for you to share the project?
If you don't want to share it here, available to everyone, I can propose to use https://uploads.jetbrains.com/ and sent here just the name of the attachment.

**Comment by Rice00** [comment]
> Would it be possible for you to share the project? If you don't want to share it here, available to everyone, I can propose to use https://uploads.jetbrains.com/ and sent here just the name of the attachment.

yeah,of course
but there's nothing different from the new project
the project is exactly the same one that pictures above shows
(Please ignore the scripts inside,it is unimportant
[GDScriptIssue.zip](https://github.com/JetBrains/godot-support/files/13440218/GDScriptIssue.zip)
thanks for your time!

**Comment by van800** [comment]
Thank you for reporting. Fix is targeting 2024.1.
Temporary workaround is to change the Runtime manually in the generated run-configuration.
![image](https://github.com/JetBrains/godot-support/assets/1482681/5995519a-e193-4fac-8ac7-434b1d26fe93)
