### ISSUE TITLE
Input/Output redirection disabled: Debugger is attached to an already running process

### ISSUE THREAD

**Issue by joshuataylor** [JetBrains/godot-support#12]
Trying to click "Start and Debug" for a fresh project shows this:

```
Input/Output redirection disabled: Debugger is attached to an already running process
/rider/lib/ReSharperHost/linux-x64/dotnet/dotnet exec //rider/lib/ReSharperHost/JetBrains.Debugger.Worker.exe --mode=client --frontend-port=45373 --plugins=
```

On Ubuntu.

The game screen pops up for a second then closes. The `Run Player` seems to work fine. Let me know what you else need?

**Comment by van800** [comment]
Duplicates #9 and #10

**Comment by van800** [comment]
Try to stop it and start again.

**Comment by joshuataylor** [comment]
Sorry for the duplicate issue. Will look in the other issues. Stop/start does not work.

**Comment by van800** [comment]
Fix is in branch, https://github.com/JetBrains/godot-support/issues/9#issuecomment-612885118
Would help a lot if you could try it a bit before publishing for everybody.
