### ISSUE TITLE
Rider on Windows doesn't show any build target.

### ISSUE THREAD

**Issue by ricardoalcantara** [JetBrains/godot-support#13]
I have been working on Linux and it was okay, I have switched to Windows and rider cannot identity the build target.

![image](https://user-images.githubusercontent.com/2466466/79053181-a3a4db80-7c11-11ea-86ca-b2fcc539f58b.png)

> JetBrains Rider 2020.1 EAP 8

**Comment by van800** [comment]
Is it Godot 3.2.1?

**Comment by ricardoalcantara** [comment]
Yes, and Rider even list it in Project Properties
![image](https://user-images.githubusercontent.com/2466466/79056625-d5786b00-7c2e-11ea-8c0e-c8c551e8b829.png)

**Comment by van800** [comment]
Does it reproduce? What if you switch it to Tools? Can you attach the csproj file here?

**Comment by ricardoalcantara** [comment]
>Does it reproduce? What if you switch it to Tools? Can you attach the csproj and sln file here?
It really feels that you have opened csproj file instead of sln file.

This last piece of information has solved my problem, I thought that it were like Visual Studio when you select a csproj it would open the sln anyway.
