### ISSUE TITLE
.Net Hot Reload works only once in a session?

### ISSUE THREAD

**Issue by qwe321qwe321qwe321** [JetBrains/godot-support#153]
It seems that it does support .NET Hot Reload for .NET 6.0+ godot project since it works on both Visual Studio 2022 and VS Code. 

In Rider, it's weird that I can only hot load once and the bottom right pops up the warning "Unable to changes" and disable the hot load feature for the current session.
![image](https://github.com/JetBrains/godot-support/assets/23000374/de0d5260-7405-4f99-a4a9-41298b7de6ca)

But it did hot loaded successfully. I'm not sure what errors happened inside.

Here is the video with a very very simple project in Rider 2024.1

https://github.com/JetBrains/godot-support/assets/23000374/847a679b-3cfb-4f7e-b69d-d794946fc4ea

I guess I am not the only one who has encountered this problem. There are some godot users having the same issue.
https://github.com/godotengine/godot-proposals/issues/7746#issuecomment-1726450281

**Comment by van800** [comment]
Unfortunately this is not something, which I can fix in a scope of this plugin.
Already reported in https://youtrack.jetbrains.com/issue/RIDER-102927/Attempting-to-hot-reload-a-C-change-using-Godot-fails-and-disables-hot-reload-for-the-rest-of-the-session-without-fail
Please vote/comment.

cc: @kugu

**Comment by maidopi-usagi** [comment]
Tested in 2024.3 EAP3, and this seems to be fixed.

**Comment by van800** [comment]
For the linux and mac, it would require a bit of manual configuration to work, please see https://youtrack.jetbrains.com/issue/RIDER-118351/C-Hot-Reload-still-non-functional-for-Godot-on-Linux#focus=Comments-27-10820611.0-0
