### ISSUE TITLE
Scene preview Tool Window not working?

### ISSUE THREAD

**Issue by RunninglVlan** [JetBrains/godot-support#172]
By accident stumbled upon new Tool Window to me - _Scene preview_. As it has the same icon as TSCN files, I guess it came from this plugin.
Didn't find any information about. How should it work?
I opened different TSCN files but it always shows _No scene_
![image](https://github.com/JetBrains/godot-support/assets/11376741/8a6fa76f-6d62-4f1e-b94a-7a9fc91cc3f3)

**Comment by van800** [comment]
It is from the "GdScript plugin", I guess.
