### ISSUE TITLE
No GdScript LSP

### ISSUE THREAD

**Issue by markusstephanides** [JetBrains/godot-support#187]
Hi,

thanks for the cool plugin!

C# support works perfectly but every .gd script I open does not have any LSP features so no proper suggestions, no go-to etc.

![image](https://github.com/JetBrains/godot-support/assets/6057570/f5b2f8d2-7e05-4d9e-896e-ad10ae1e40df)

The toolbar says that Rider is connected to the editor but I don't know if I need to check/setup additional things (the LSP port is correct) 
When developing in VSCode, everything works normally.

The tabs of files like enemy.gd also look like they don't belong to the project, not sure if this is intended or not (I can't find them when searching for Files in the Navigation)
![image](https://github.com/JetBrains/godot-support/assets/6057570/defba93e-cb00-4a61-8fe5-30e7e69b06b3)

Would appreciate help, thank you very much!

**Comment by van800** [comment]
We have found a case, that LSP doesn't fire, when gd file is not included in csproj.
This problem was already addressed, you may expect it around EAP6/EAP7.
For now, as a workaround you may include gd files in the csproj.

**Comment by van800** [comment]
https://github.com/JetBrains/godot-support/pull/186

**Comment by markusstephanides** [comment]
Thank you very much!
