### ISSUE TITLE
Provide a context menu item on every tscn with ability to run game with this scene

### ISSUE THREAD

**Issue by van800** [JetBrains/godot-support#2]
Resulting commandline should look like 
`"C:\Work\godot2\bin\godot.windows.opt.tools.64.mono.exe" "--path" "D:/Work/Deathville" "--remote-debug" "127.0.0.1:6007" "--allow_focus_steal_pid" "2776" "--position" "0,60" "res://scenes/Spatial.tscn"`

**Comment by Duroxxigar** [comment]
This is how I imagine it to work...

1) Debug in Rider
2) Dialogue pop up with a list of all .tscn files in the Godot directory
3) Select the tscn to debug - with a remember checkbox (or somethin' like that)
4) If no tscn is selected, the main scene would get ran.

Or something like this. It would get quite tedious to have to change the "res://scenes/Spatial.tscn" by hand so frequently. Sometimes, you just want to test an individual tscn file. I couldn't find an individual file in Godot's project that has a list of all .tscn files to read from, so perhaps a search through all of the "res://" directory for all .tscn files would work?

**Comment by Reneator** [comment]
@Duroxxigar or maybe you could create a run-config in Rider that is set to run the desired .tscn?

**Comment by van800** [comment]
@Reneator for sure manual creating is possible, but we want to improve quality of life.

**Comment by van800** [comment]
fixed in plugin .36, which targets 2020.2 EAP5+
