### ISSUE TITLE
Hot Reload doesn't seem to work.

### ISSUE THREAD

**Issue by KShivum** [JetBrains/godot-support#209]
Hi, so I'm using Rider 2024.1.6 on Arch KDE Wayland and I cannot get the hot reload popup to show up when making changes to a cs file in Godot. I quickly went and checked, and it still works in a console application, but it doesn't work in a .Net 8 Godot 4.2.2 project.

**Comment by van800** [comment]
please see https://youtrack.jetbrains.com/issue/RIDER-102927/Attempting-to-hot-reload-a-C-change-using-Godot-fails-and-disables-hot-reload-for-the-rest-of-the-session-without-fail
and https://youtrack.jetbrains.com/issue/RIDER-118351/Simplify-C-Hot-Reload-for-Godot-on-nix

**Comment by van800** [comment]
fixed in 2024.3. EAP 3
