### ISSUE TITLE
Cannot debug default "Player" configuration in Rider 2024.2 with Godot 3

### ISSUE THREAD

**Issue by xill47** [JetBrains/godot-support#211]
Same configuration used to work with in 2024.1 (so before bundling)

The configuration: 

![image](https://github.com/user-attachments/assets/c6c80eba-6a25-4c2e-9257-69f0aa38e776)

The error: 

![image](https://github.com/user-attachments/assets/3930aee3-bcdf-4319-a7d5-192db19b5f25)

I can run configuration fine and then attach debugger to it

**Comment by van800** [comment]
Thank you for reporting. The same came today from the Rider support channel. https://youtrack.jetbrains.com/issue/RIDER-116030
Fix should be available soon.
In the meantime please use Rider 2024.1.x

**Comment by van800** [comment]
Fixed some time ago, just closing the issue now.
