### ISSUE TITLE
GScript hot reload need refocus

### ISSUE THREAD

**Issue by m21-cerutti** [JetBrains/godot-support#216]
Hello,
Seems Hot reloading (maybe link to https://github.com/JetBrains/godot-support/issues/209) doesn't work out of the box.

When editing a GDScript with the game run, I would expect like in the internal Godot Editor that the code is reloaded when I save the file. Tosome extent, when a GDScript is saved even in Rider, it should trigger hot reloading.

But what I need is to refocus on the Godot Editor for changes to be effectively reloaded.
There is also a annoying dialog that  ask to reload the script accordingly, that shouldn't occur.
![image](https://github.com/user-attachments/assets/691da273-a43a-451f-bc03-985e0f11aeec)

Here a video showing the problem:
https://github.com/user-attachments/assets/dacf9392-7b92-48b4-9509-2fbfe43bb37b

**Comment by van800** [comment]
fixed in the 2024.3 release https://youtrack.jetbrains.com/issue/RIDER-114380/Godot-HotReload-GDScript

**Comment by nigel-dev** [comment]
So this appears to have regressed. I have to refocus the Godot editor for the hot reload to apply. I dont get that popup window like in the previous video, but the effect is the same. 

Im Sequoia 15.5 on a Macbook Pro M4 Max. 

Video:
https://github.com/user-attachments/assets/9d44c71e-7c3a-4dcc-af94-c27d0ac8369d

Godot:
```
v4.4.1.stable.official [49a5bc7b6]
```

Rider:
```
JetBrains Rider 2025.1.2
Build #RD-251.25410.119, built on May 7, 2025
Source revision: d31f38dce07eb

Runtime version: 21.0.6+9-b895.109 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 15.5
.NET Core v8.0.11 ARM64 (Server GC)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 16
Metal Rendering is ON
Registry:
  ide.balloon.shadow.size=0
  suggest.all.run.configurations.from.context=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  editor.minimap.enabled=true
  llm.show.ai.promotion.window.on.start=false
Non-Bundled Plugins:
  com.intellij.aqua (251.25410.109)
  ice.explosive.gdscript (2.7.0)
  org.jetbrains.plugins.gitlab (251.25410.159-IU)
  org.jetbrains.plugins.github (251.25410.159-IU)
  com.mallowigi (101.2.0)
  com.fapiko.jetbrains.plugins.better_direnv (1.2.2)
  com.chrisrm.idea.MaterialThemeUI (9.8.1)
  zielu.gittoolbox (600.1.2+243)
  net.seesharpsoft.intellij.plugins.csv (4.0.2)
  me.rafaelldi.aspire (1.7.10)
  izhangzhihao.rainbow.brackets (2024.2.11-241)
```

**Comment by van800** [comment]
@nigel-dev we will take a look 
Please follow https://youtrack.jetbrains.com/issue/RIDER-126417/Possible-regression-Godot-hot-reload
