### ISSUE TITLE
Game output in rider instead of separate terminal

### ISSUE THREAD

**Issue by hhyyrylainen** [JetBrains/godot-support#22]
I'd like the game output to be visible in the process output in rider, instead of it opening a separate terminal with the output. When the game exits the terminal also closes, making all the output disappear.
https://github.com/JetBrains/godot-support/issues/10#issuecomment-627301665

**Comment by Meister1593** [comment]
If it's not possible to write into rider terminal, then it would be nice to detach actual console from process in case it exits. Maybe attaching terminal to rider would be better
