### ISSUE TITLE
Cannot attach to player/Godot

### ISSUE THREAD

**Issue by MeikelLP** [JetBrains/godot-support#224]
I'm fairly new to Godot but kinda advanced in Rider

I cannot debug my C# code with Rider.
![Screenshot_20241023_221222](https://github.com/user-attachments/assets/bf1c7a1a-c6d6-46ac-8242-1bd8cc2a7cda)

I also cannot start the Godot Editor from within Rider - even when it's not open

My Specs:

* OS: Debian12
* Rider: 2024.2.6
* Godot: 4.3 (Flathub)

What else info can I post you?

**Comment by van800** [comment]
I think flatpack sandbox is not supported.

**Comment by van800** [comment]
We can check couple of things though.
<img width="1356" alt="image" src="https://github.com/user-attachments/assets/d1c67bda-aa4e-44fc-92cd-c3bfde75de5c">

What executable_path do you have in the project_metadata.cfg? Is it runnable from the console, outside flatpack? Does it have an executable permission?

**Comment by MeikelLP** [comment]
The path is `/app/bin/godot-bin` which is not a valid path I assume.

The executable is at `/var/lib/flatpak/app/org.godotengine.GodotSharp/current/active/files/bin/godot`

**Comment by van800** [comment]
I am afraid that flatpack would not be supported in the foreseeable future.
Please use an official Godot distribution from the website. Locally compiled is also supported.

**Comment by MeikelLP** [comment]
That's a shame. I really like the flatpak philosophy but I can understand why it's not possible
