### ISSUE TITLE
Autocomplete "res://" paths

### ISSUE THREAD

**Issue by atomicptr** [JetBrains/godot-support#39]
Scenario:

When trying to e.g. load a PackedScene

```csharp
var scene = GD.Load<PackedScene>("res://...");
```

It would probably be very useful to get suggestions for path segments instead of having to rely on your memory to type them out correctly.

**Comment by van800** [comment]
Implementation might be something similar to https://plugins.jetbrains.com/plugin/11088-file-path-autocomplete, https://github.com/PinkFloyded/idea-file-path-autocomplete
