### ISSUE TITLE
Completion for NodePath arguments of Godot.Node.GetNode calls

### ISSUE THREAD

**Issue by van800** [JetBrains/godot-support#4]

**Comment by AndrewMorsillo** [comment]
This is now available in Visual Studio with Godot 3.2.3. Would it also be possible to check for invalid node names? Having design-time warnings about misspelled or moved node names would be excellent.

**Comment by van800** [comment]
related https://github.com/JetBrains/godot-support/issues/39

**Comment by AndrewMorsillo** [comment]
@van800 Here's the source for the Visual Studio implementation of NodePath autocomplete. I'm guessing a lot of this could probably be reused for Rider? https://github.com/godotengine/godot-csharp-visualstudio

**Comment by K1ll3rM** [comment]
This would be very nice to have

**Comment by fahall** [comment]
Any updates on this? It would significantly improve the user experience. Not having node/res path autocompletion is the thing I miss most about other Godot IDEs

**Comment by van800** [comment]
Nothing at the moment.

**Comment by jsbeckr** [comment]
Can be closed (#102)
