### ISSUE TITLE
Rider asks to enable plugin each time I start it

### ISSUE THREAD

**Issue by nathanjwtx** [JetBrains/godot-support#41]
Rider 2020.2 EAP 8
Windows 10

Each time I open a Godot project, Rider asks me to enable the plugin even though it is already enabled.

Next time it happens I'll add a screenshot.

**Comment by van800** [comment]
It is expected to be fixed in EAP9. Haven't yet tested.

**Comment by van800** [comment]
Just checked. Once EAP9 or release is out - it should be fine.
