### ISSUE TITLE
Run error on Godot .exe name change (minor issue)

### ISSUE THREAD

**Issue by muemmel** [JetBrains/godot-support#43]
First off, great plugin. Thanks very much for this.

Stumbled upon this issue when adding Godot to my Path variables and renaming the engine's executable to something more easily typed. Creating a new project Godot project and trying to debug it with Rider, however, went flawlessly.

I'm guessing the executable's path is just not re-discovered when it's not found, so I had to change the according values in the workspace.xml.

**Comment by van800** [comment]
Do you mean, 
1. Rename/move Godot executable somewhere
2. Open project in GodotEditor
3. Open Rider 
should automatically re-check that path to Godot executable is valid and fix it if needed?

I tried to deal with nearly that in https://github.com/JetBrains/godot-support/pull/40, however didn't have time to properly finish.

**Comment by muemmel** [comment]
Your described way does work.

The error occurs when opening the project only in Rider and trying to 'Start and Debug'. I guess I misinterpreted #40, since the Project had already been opened in the Godot Editor, just not after changing the the executable's name/location.

**Comment by van800** [comment]
Would be nice to have a step-by-step sequence, which didn't work for you.

**Comment by muemmel** [comment]
Rename/Relocate Godot Executable.
Start Rider and Run the solution.
Rider can't find the executable.

My fumbling around with the workspace.xml was due to me not realizing that reopening the project in the Godot Editor fixes the issue. So the issue is even more minor. :)

**Comment by van800** [comment]
In the described case, I don't see how Rider can guess where Executable was relocated.

**Comment by muemmel** [comment]
I honestly don't know. I didn't look into the source, so I thought there was some special voodoo behind locating the executable. Thanks for hearing me out anyway. Guess you can close this. 👍
