### ISSUE TITLE
Error when trying to start the project with Debug

### ISSUE THREAD

**Issue by nathanjwtx** [JetBrains/godot-support#53]
I haven't started this project for a couple of months but I'm fairly confident this was working previously. I can start the project/editor from Rider but I can't debug it.

Windows 10 Pro Build: 19042.610
NVidia GTX 1050
Godot 3.2.2 Stable - Mono
Rider 2020.3 EAP 5
Godot Plugin 2020.3.49

I get the following error message using any of the run configurations:

`Error running 'Editor': loader constraint violation for class com.jetbrains.rider.plugins.godot.run.configurations.GodotDebugProfileState: when selecting overriding method 'java.lang.Object com.jetbrains.rider.plugins.godot.run.configurations.GodotDebugProfileState.createWorkerRunInfo(com.jetbrains.rd.util.lifetime.Lifetime, com.jetbrains.rider.debugger.DebuggerHelperHost, int, kotlin.coroutines.Continuation)' the class loader com.intellij.ide.plugins.cl.PluginClassLoader @480c2b41 of the selected method's type com.jetbrains.rider.plugins.godot.run.configurations.GodotDebugProfileState, and the class loader com.intellij.util.lang.UrlClassLoader @6500df86 for its super type com.jetbrains.rider.run.configurations.remote.MonoConnectRemoteProfileState have different Class objects for the type kotlin.coroutines.Continuation used in the signature (com.jetbrains.rider.plugins.godot.run.configurations.GodotDebugProfileState is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @480c2b41, parent loader 'bootstrap'; com.jetbrains.rider.run.configurations.remote.MonoConnectRemoteProfileState is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @6500df86, parent loader 'platform')`

**Update**
I re-installed the latest release version of Rider, 2020.2.4 (plugin version 2020.2.38), and I can successfully launch my game for debugging etc.

**Comment by van800** [comment]
Thank you for reporting, reproduced.

**Comment by van800** [comment]
Fixed with plugin rider-godot-2020.3.50.zip
