### ISSUE TITLE
"GodotPath is unknown." error message when trying to run NUnit tests

### ISSUE THREAD

**Issue by derkork** [JetBrains/godot-support#68]
I'm trying to run NUnit tests using the plugin. I have installed the support files as indicated, however when I run a test I get the following output:

```
--- EXCEPTION #1/2 [InvalidOperationException]
Message = “GodotPath is unknown.”
ExceptionPath = Root.InnerException
ClassName = System.InvalidOperationException
HResult = COR_E_INVALIDOPERATION=80131509
Source = JetBrains.ReSharper.Plugins.Godot
StackTraceString = “
  bei JetBrains.ReSharper.Plugins.Godot.UnitTesting.GodotTestRunnerHost.GodotPatcher.Patch(JetProcessStartInfo startInfo, JetProcessRuntimeRequest request) in Z:\buildAgent\work\d86184d35b2f7761\resharper\src\UnitTesting\GodotTestRunnerHost.cs:Zeile 114.
```

I have not found any setting where I could set up the path to the Godot executable.

**Comment by van800** [comment]
Does running a game via run-configuration work?
![image](https://user-images.githubusercontent.com/1482681/134856109-9b6fb67d-689d-4bb6-b49c-f30bfefd7d9a.png)

**Comment by derkork** [comment]
Yes this works. Interestingly enough these run configurations have an empty value for the godot executable.

**Comment by derkork** [comment]
How is the godot executable actually detected? I have found no setting to set this up so it is probably auto-detected somehow.

**Comment by van800** [comment]
In case, if the project was opened at least once in the Godot Editor, we should be able to guess the path by [this code](https://github.com/JetBrains/godot-support/blob/net212/rider/src/main/kotlin/com/jetbrains/rider/plugins/godot/GodotServer.kt#L16)

And UnitTesting should use path, which is set in the Player run configuration.

Does it all works now, after you fixed the path in the Player run configuration?

**Comment by derkork** [comment]
After I fixed the path in the run configuration (i changed both to be sure) and restarting Rider & Godot I can now run tests from the IDE.
