### ISSUE TITLE
Xunit testing opens Project Manager instead of Runner.tscn when order issued from Cloud Drive

### ISSUE THREAD

**Issue by jjgmcken** [JetBrains/godot-support#69]
Re: https://github.com/JetBrains/godot-support/pull/58

I'm sorry if this is the wrong place for this, but whenever I try to use the Xunit testing integration in the Rider client, it doesn't open the .tscn file, and instead only opens the Godot Project Manager, leaving the tests hanging until the project manager is closed, where they report as "Inconclusive, test not run"

**Comment by van800** [comment]
Please attach a minimal repro project.

**Comment by jjgmcken** [comment]
@van800 Hi there. I finally nailed down the cause of this while making a minimal reproduction project and trying to figure out the cause more thoroughly. 

I have the Godot path saved on my C:/ drive, whereas I save the project on cloud storage, a "G:/ "Google Drive. Xunit testing works when the two are on the same drive, but does not when they are not. Launching/compiling is unaffected. 

I'm unsure if it is the fact it is cross-drive that is the issue or whether or not it is to do with cloud storage; either way I will amend the issue's title for clarity.

**Comment by van800** [comment]
I have tried to reproduce the issue, I made a subst to X drive, but everything works fine.
Not sure, what is specific in your case.
When you start tests in Rider it runs Godot.exe with args, it can be seen in a tool like ProcessExplorer. Could you please check what arguments does it pass?
![image](https://user-images.githubusercontent.com/1482681/148401323-337dd649-8e1a-41f0-860e-8d02de06d446.png)

**Comment by van800** [comment]
Please reopen if it still reproduces for you.
