### ISSUE TITLE
Warn in case when run configuration points to different godot version

### ISSUE THREAD

**Issue by van800** [JetBrains/godot-support#70]
Usually after updating Godot to different version, updating run-configurations is also needed.
But we can't be sure, that it is intended, so maybe show a Warning with explicit action to fix the path.

**Comment by van800** [comment]
Example of such a notification:
https://github.com/JetBrains/resharper-unity/blob/a06aaf99cd23a7f0a06845bfa401b4bbfb11e60f/rider/src/main/kotlin/com/jetbrains/rider/plugins/unity/notifications/OpenUnityProjectAsFolderNotification.kt#L80

Example of changing a run configuration:
https://github.com/JetBrains/godot-support/blob/bd246d0043c477b7b299fed50ee1b85c46db0e65/rider/src/main/kotlin/com/jetbrains/rider/plugins/godot/run/GodotRunConfigurationGenerator.kt

**Comment by benjacksondev** [comment]
Hi, can I pick this up? @van800

**Comment by van800** [comment]
Sure! @benjacksondev
