### ISSUE TITLE
Unable to load maven meta data 

### ISSUE THREAD

**Issue by benjacksondev** [JetBrains/godot-support#72]
I get the following error when I try and run `./gradlew runIde` from the Rider dir. 

Unable to load Maven meta-data from https://cache-redirector.jetbrains.com/dl.bintray.com/kotlin/kotlin-eap/com/jetbrains/intellij/rider/riderRD/2021.3-SNAPSHOT/maven-metadata.xm.

I have  cloned the project, following instructions in Contributors.md

**Comment by van800** [comment]
Thank you for reporting. 
Just pushed the fix to net213. https://github.com/JetBrains/godot-support/commit/94711962b3455e753399e9def9f27a992fec4140
