### ISSUE TITLE
Unexpected Debugger Step-Into locations

### ISSUE THREAD

**Issue by Flavelius** [JetBrains/godot-support#74]
Sometimes when using the debugger's 'Step-into' rider ends up/stops in some property getter or method that's one line below the first instructions of the method that's being stepped into. And sometimes it even steps into some system call (so far for me they were inside linq internals) or thirdparty code (fluentassertions internals), so basically it then ends up in a semi random location.
But then it at times also varies between runs/after changes to something unrelated, meaning sometimes it does step to the expected location.

And maybe it's related: in some unit tests it also ended up in if i remember correctly 'Reflect.cs' (in try-catch for targetinvokationexception) which seemed to be some rider internal thing, when an assertion was triggered while running them in debug configuration instead of breaking at the expected location where it's triggered (when run normally they seem to end with the correct assertions, even though the runtime doesn't exit by itself afterwards - which may be another issue)

**Comment by van800** [comment]
Hi! Can I ask you to report this with Help->Report a Bug in Rider and agree to attach logs?
The issue is related mostly to the mono debugger in Rider core, not in this plugin.
Thank you!

**Comment by Flavelius** [comment]
Okay, i thought it belonged here because this only happens when using rider with godot.

**Comment by van800** [comment]
Same would likely reproduce with Unity and any other mono application.
