### ISSUE TITLE
After ending a Godot 3.5 Run/Debug launch in Rider 2022.2 (Linux), I can no longer add new classes/directories/etc in solution or file system tool windows until Rider is restarted

### ISSUE THREAD

**Issue by lewiji** [JetBrains/godot-support#78]
* Godot version: `Godot_v3.5-stable_mono_x11.64` official binary
* OS: Linux 5.18 EndeavourOS
* Rider 2022.2
* Godot Support 2022.2.90 plugin version

On initially opening the project in Rider, everything works as normal. When I launch the game using the Player configuration either via Run or Debug, after the process/debugging session has ended, I'm no longer able to add new classes/directories to the solution - the option is greyed out.

![image](https://user-images.githubusercontent.com/233380/183263136-9e3ef705-bf27-455f-81d8-b10a41f2ca55.png)

Running a **non-Godot**, regular C# project doesn't produce the same behaviour, so far this seems to be only when using the Godot Support plugin launch configurations.

I updated both Godot and Rider last night, so I'm unsure which is responsible, but I have been using the Godot 3.5 RC versions for the last month without issue, so I suspect it's to do with the new Rider version. 

Incidentally (probably unrelated, but just in case relevant), when I tried to rollback Rider via Toolbox just now to check, I got the message that the downgrade failed because Rider was still running, despite no Rider-related processes running on the system that I could find via htop/KSysGuard. Which leads me to think that maybe there's some issue with the latest JB versions and detecting running processes on my system that are causing these problems. Going to reboot, downgrade Rider and try again, and will edit the issue with the results.

Edit: 

* Downgrading to Rider 2022.1.2, and reinstalling the Godot Support plugin, I can no longer reproduce the problem. 
* Upgrading to Rider 2022.2 again reproduces the problem.

So definitely seems to be related to Rider 2022.2, and I'm fairly sure this is only occurring with the Godot Support plugin launch configurations, though I don't know enough about Rider plugins to dig in further and get any debug info.

**Comment by lewiji** [comment]
Ah, I just noticed the `net222` branch which looks like it may have already fixed this issue - though trying to build the plugin locally caused a gradle failure: `Task :buildReSharperPlugin FAILED`

I'm just going to rollback Rider for now, and wait for the release of that branch :)

**Comment by van800** [comment]
Its https://youtrack.jetbrains.com/issue/RIDER-79708/Cant-add-or-remove-files-after-running-app
Would be fixed with Rider hotfix, I guess.

**Comment by lewiji** [comment]
Thanks! Apologies, I did try a non-godot project as a test case which worked fine, but I just realised that project had a different non-standard launch config so must have avoided the bug some other way.
