### ISSUE TITLE
Ability to 'Start and Debug' with Godot Headless version.

### ISSUE THREAD

**Issue by ricardoalcantara** [JetBrains/godot-support#8]
With 'Run Player' I have the ability to change the binary to use my headless version, but for 'Start and Debug' there is no such a options, I use headless version because I am programming the server version on my game and I don't need any interface.

**Comment by van800** [comment]
how do you run your version? some commandline argument or different executable?

**Comment by ricardoalcantara** [comment]
Godot also provides two extra versions here https://godotengine.org/download/server
- **Headless** is the editor without GUI, for command line and I run my server game for tests with it, so I can debug with mono attach. (https://docs.godotengine.org/en/stable/getting_started/editor/command_line_tutorial.html)
- **Server** is the exported version, the final game but also without GUI, so you can export the linux version and replace the binary and deploy on your server machine.


> Obs. Both it Linux only binaries.

**Comment by van800** [comment]
Maybe with Godot 3.2.2 and with help of this PR https://github.com/godotengine/godot/pull/36993
Your problem would be resolved?

**Comment by van800** [comment]
Lets either wait 3.2.2 or you can compile it locally and check.

**Comment by ricardoalcantara** [comment]
I don't think so, I also use the editor. To edit anything in the server project I use the normal Editor (Create scene, add script to a scene, change nodes...), I could also press play in this editor and it would open a gray empty screen, But I don't need it, so I go to the terminal and run the project with the headless version, and attach the debug on it, and after that I alter to the client game and press play on it too, but Godot usually bind a port 6007 for internal usage on it's debug, so even If I press Play in both editor the second one display a warning and don't catch any print in terminal. This suggestion it just for easiness.

**Comment by van800** [comment]
Do I understand right, that your headless and server runners may theoretically be anywhere on the machine? And there is no automatic way to detect their location?

**Comment by ricardoalcantara** [comment]
Let's forget the server for a moment because it's not meant to be used with the editor or debugging, I explained it because people usually get's confused with those two binaires. 

> Do I understand right, that your headless and server runners may theoretically be anywhere on the machine? And there is no automatic way to detect their location?

I guess so, and I don't mind because I am turning the game in a server version so I just want to change the path in the profile, so the play button starts godot-headless instead godot to execute the game.

**Comment by ricardoalcantara** [comment]
Still this godotengine/godot#36993 will not be useful because on my desktop Linux I have godot at /usb/bin/godot on my notebook it's in $USER/Application/godot... and on my Windows it's on D:\opt\godot...

**Comment by ricardoalcantara** [comment]
On windows
```
java.io.IOException: Cannot run program "": CreateProcess error=87, The parameter is incorrect
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.jetbrains.rider.plugins.unity.run.configurations.GodotDebugProfileState$execute$1.run(GodotDebugProfileState.kt:37)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:20)
	at com.intellij.util.RunnableCallable.call(RunnableCallable.java:11)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.call(ApplicationImpl.java:255)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.IOException: CreateProcess error=87, The parameter is incorrect
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 9 more
```

In this case the Godot 3.2.2 fix will work, but still I could just setup the Godot binary path myself.

**Comment by van800** [comment]
@ricardoalcantara I have added handling for that last exception. https://github.com/JetBrains/godot-support/pull/15/commits/2ee430288f44698993c9536c6fd717577dc8d779
In Godot 3.2.1 it may happen, when Godot Editor is not running.

**Comment by van800** [comment]
There would not be fix for Headless version soon.
So here is a workaround:
1. Copy `Run Player` configuration into `Run Player, wait for attach`
2. Add env.var:
`"GODOT_MONO_DEBUGGER_AGENT", "--debugger-agent=transport=dt_socket,address=127.0.0.1:50014,server=n,suspend=y"`
3. Add new `Mono Remote` configurations `Attach to Headless`, set port to 50014.

Now you would be able to start your headless Godot with one configuration and Attach with another one. 

I hope core Rider will make a better fix for this in 2020.2, see https://youtrack.jetbrains.com/issue/RIDER-42273

**Comment by ricardoalcantara** [comment]
It's easier to keep on running from the terminal and use a simple attach. I don't need to set any configuration for that.

**Comment by van800** [comment]
Sure, just for the case, if you would need to debug very startup one day.

**Comment by ricardoalcantara** [comment]
> Sure, just for the case, if you would need to debug very startup one day.

It's good to know another option for that, I was using another options in Godot that waits attach. Thanks!

**Comment by van800** [comment]
fixed in plugin .36, which targets 2020.2 EAP5+

**Comment by van800** [comment]
EAP5 is available today.
![image](https://user-images.githubusercontent.com/1482681/86492024-f30c2b00-bd6c-11ea-9057-5b3576d5f0e4.png)
