### ISSUE TITLE
GD0001: partial modifier static analysis for Godot 4

### ISSUE THREAD

**Issue by Sythelux** [JetBrains/godot-support#81]
Godot 4 now requires anything inheriting from Godot.Object to be partial. The Plugin doesn't recognise this, yet

example code: 

```
public class Main : Node3D
{
	public override void _Ready()
	{
		GD.Print("_Ready");
	}
}
```

This looks fine in Rider, but when building in Godot it yields:

>[...]\Main.cs(4,1): Error GD0001 : Missing partial modifier on declaration of type 'Main' which is a subclass of 'Godot.Object'

It would be good to have a static analysis of Rider to show that error in the editor before building.

**Comment by van800** [comment]
I think it might be worth implementing such a roslyn analyser in the Godot source itself, somewhere near [the source generator, which produces that error](https://github.com/godotengine/godot/blob/f70e106010e10451822ba8f526fdcc7b60fa2981/modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/ScriptSignalsGenerator.cs#L49).
That way all IDE-s (including Rider) would automatically display the error.

**Comment by Sythelux** [comment]
> I think it might be worth implementing such a roslyn analyser in the Godot source itself, somewhere near [the source generator, which produces that error](https://github.com/godotengine/godot/blob/f70e106010e10451822ba8f526fdcc7b60fa2981/modules/mono/editor/Godot.NET.Sdk/Godot.SourceGenerators/ScriptSignalsGenerator.cs#L49). That way all IDE-s (including Rider) would automatically display the error.

can you point me to a typical roslyn implementation in another repo or the Roslyn doc for that? This sounds like an Issue I would be able to solve in the core.

**Comment by van800** [comment]
Try looking in https://github.com/microsoft/Microsoft.Unity.Analyzers

**Comment by van800** [comment]
Should be implemented in the engine similar to https://github.com/godotengine/godot/pull/79007

**Comment by van800** [comment]
I have started making a pull request https://github.com/godotengine/godot/pull/87253, however got a problem with testing it.

**Comment by van800** [comment]
Merged today.

**Comment by Sythelux** [comment]
I followed the discussions about it in the godot project and the refactoring it lead to. Thank you a lot of taking care if it!
