### ISSUE TITLE
Breakpoints are not hit in Godot 4 Beta 1

### ISSUE THREAD

**Issue by Byteron** [JetBrains/godot-support#82]
When using Godot 4 Beta 1 and the Godot Plugin in Rider, I can set breakpoints, but when starting the project via the debug button, it says ... okay well. In the last version it was still running, but the breakpoints were greyed out. I *just* updated the godot plugin, and now it outright says the profile is not supported.
![image](https://user-images.githubusercontent.com/24433899/191176585-af2fa950-2623-4b25-9c1a-f608f1a3aaf4.png)

**Comment by Byteron** [comment]
Okay, there now is two profiles each, one with the godot logo, and the other profiles work, including hitting breakpoints and stuff. thanks!

**Comment by van800** [comment]
Yeah, it makes sense to remove the old configurations automatically for Godot_net6, but need to keep them, in case of Godot 3.5.
Haven't yet found a good solution.
