### ISSUE TITLE
Breakpoint doesn't work - "Didn't find the associated module for the breakpoint"

### ISSUE THREAD

**Issue by roookeee** [JetBrains/godot-support#83]
I am running into an issue where breakpoints aren't working when I start the player via the "Player" run configuration:
![image](https://user-images.githubusercontent.com/1199562/191469184-c02e8fca-57bd-4cb5-9de9-6ab66d1e4fcb.png)
I tried setting / unsetting myriads of rider specific .NET debugging setting but nothing helps.
Here is a sample project [sample.zip](https://github.com/JetBrains/godot-support/files/9615231/sample.zip).
This is on [Godot_v4.0-beta1_mono_win64](https://downloads.tuxfamily.org/godotengine/4.0/beta1/mono/), Rider 2022.2.3 and plugin version 2022.2.98.

I haven't tested Godot 3 yet so I can't assess if this is a 4.0 beta only issue. Is there anything I need to configure? My main project is running fine otherwise.

**Comment by van800** [comment]
Please attach logs, get them by the `Help->Collect logs` command in Rider.

**Comment by van800** [comment]
Ah, I have understanding, what happens.
Please change the run-configuration from the one with the Godot icon to the `Player` without Godot icon.

**Comment by roookeee** [comment]
@van800: I don't have any run configuration without a Godot icon:
![image](https://user-images.githubusercontent.com/1199562/191475052-ffab244a-b392-4fc6-aebd-f85e7c4a6c57.png)
Let me know if you still need the logs

**Comment by van800** [comment]
What Rider version do you have?

**Comment by roookeee** [comment]
As noted in my initial post:
> This is on [Godot_v4.0-beta1_mono_win64](https://downloads.tuxfamily.org/godotengine/4.0/beta1/mono/), Rider 2022.2.3 and plugin version 2022.2.98.

**Comment by van800** [comment]
Have you opened the project in the Godot Editor?
I expect the file `.godot/editor/project_metadata.cfg` to be created by the Editor.

**Comment by roookeee** [comment]
I have opened the project, yes. Furthermore the file is preset, here is my `.godot` folder: 
[sample-dot-godot.zip](https://github.com/JetBrains/godot-support/files/9615501/sample-dot-godot.zip)

**Comment by van800** [comment]
Is it the existing file on your file-system? `D:/dev/Godot_v4.0-beta1_mono_win64/Godot_v4.0-beta1_mono_win64/Godot_v4.0-beta1_mono_win64.exe`

**Comment by roookeee** [comment]
Yes that file exists, the player wouldn't start without it anyway right? It starts, just the breakpoints aren't working.
 
![image](https://user-images.githubusercontent.com/1199562/191477806-79adc591-69d7-435e-a880-75ac9c9fcf9b.png)

**Comment by roookeee** [comment]
Can you upload the expected run configuration here so I can check if it would work. Weird that they aren't getting generated for me and I have the old ones. I downloaded the plugin before updating my IDE 2 days ago which probably updated the plugin as well but that shouldn't cause issues for new projects, right?

**Comment by van800** [comment]
Try to close Rider and open again - it may finally regenerate run configuration.
Otherwise as a temporary workaround you may create a `.Net Executable` run configuration in Rider with all the arguments from the existing `Player` run configuration and Runtime: ".Net/.NetCore".

**Comment by van800** [comment]
I have just rechecked the workflow on my windows system - it worked as expected.
Please still attach those logs Help->Collect logs, could be some pointer there.

**Comment by roookeee** [comment]
Creating the manual run configuration with the .net core runtime worked but the run configuration is not regenerated for me when I reopen Rider. So this fixes the issue for me.

Here are my IDE logs before I created the manual run cfg (I will delete these later because of personal data stuff, let me know if a thumbs up when you downloaded them):
[rider-logs-20220921-11541413877659778322278925.zip](https://github.com/JetBrains/godot-support/files/9615628/rider-logs-20220921-11541413877659778322278925.zip)

**Comment by van800** [comment]
I have got them

**Comment by van800** [comment]
Logs say: Godot Support (2021.1.69).

**Comment by van800** [comment]
Please update in Setting->Plugins
![image](https://user-images.githubusercontent.com/1482681/191480169-4ee715ac-8742-4ff0-860f-e090a7535603.png)

**Comment by roookeee** [comment]
:O It didn't offer me to update the plugin before. Wow, what a dumb oversight, sorry for the hassle!

Thank you for the help!
