### ISSUE TITLE
Run/Debug button appearance bug

### ISSUE THREAD

**Issue by PandoCyclone** [JetBrains/godot-support#85]
The button outline got deleted when i switch between runs

![image](https://user-images.githubusercontent.com/81963564/200101027-7aa2b002-801a-433f-b316-8e8353eeb175.png)
![image](https://user-images.githubusercontent.com/81963564/200101069-43f208f0-25e4-4173-96ea-e3ba60a7911d.png)

**Comment by PandoCyclone** [comment]
Btw the bug also happen in normal theme

**Comment by van800** [comment]
Is it specific to the Godot plugin?

**Comment by PandoCyclone** [comment]
> Is it specific to the Godot plugin?

Normal console is fine but if i switch between "Mono for debug" and "Godot editor/player" that would happen, but after a while or if I click reset tool bar it turn normal then happen again

**Comment by PandoCyclone** [comment]
Hope it got fixed soon :D

**Comment by PandoCyclone** [comment]
Thank you
