### ISSUE TITLE
Implement input map suggestion

### ISSUE THREAD

**Issue by Perndoe** [JetBrains/godot-support#86]
Rider is thinking everything in side quotation mark is a string so it doesn't suggest anything

In VSCode it looks like this:
![image](https://user-images.githubusercontent.com/81963564/201369060-4eeda05b-2f8a-4e26-87a7-b94d0870e846.png)

I think that would be cool

**Comment by van800** [comment]
What are those? Could you please attach example script or project?

**Comment by geowarin** [comment]
Those are Input Maps, defined in project settings:

![image](https://user-images.githubusercontent.com/1045636/201399025-049965b1-da5e-4e79-a671-35a67fc32fea.png)

They are store in `project.godot`:

```
move_forward={
"deadzone": 0.5,
"events": []
}
move_back={
"deadzone": 0.5,
"events": []
}
move_left={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":68,"unicode":0,"echo":false,"script":null)
]
}
move_right={
"deadzone": 0.5,
"events": [Object(InputEventKey,"resource_local_to_scene":false,"resource_name":"","device":0,"window_id":0,"alt_pressed":false,"shift_pressed":false,"ctrl_pressed":false,"meta_pressed":false,"pressed":false,"keycode":0,"physical_keycode":65,"unicode":0,"echo":false,"script":null)
]
}
```

Autocomplete would need to be displayed when using various method of the `Input` class that take `StringName action` as a parameter.

**Comment by Intrivus** [comment]
The thing is not only does the input map not showing but also everything in quotation marks/string will not show suggestions
Namely: nodes' name

**Comment by MikadoDev1399** [comment]
The IDE doesn't help with the following situations:-
1- Getting input action name.
2- Getting resource path (res://scenename.tscn)
3- Getting the signal name when you want to connect.
4- Getting node path when you call "get_node".

The normal Godot engine IDE provide support for that, and I think the Godot extension for VScode.  Allow me to demonstrate that.

**[1]: Getting Input action name from the input action map in project setting:-**

Godot IDE
![image](https://user-images.githubusercontent.com/98526116/210026705-f7c05e83-f1f4-49bb-a434-cac30816c798.png)

Project setting input map
![image](https://user-images.githubusercontent.com/98526116/210026762-b62fe587-c212-42a2-9dff-095caa5e5010.png)

**[2]:  Getting resource path (res://scenename.tscn):-**

![image](https://user-images.githubusercontent.com/98526116/210026834-589da088-4b6e-4a3e-a3dc-c634eb0b5d61.png)

![image](https://user-images.githubusercontent.com/98526116/210026864-1f0ca11f-995f-4458-85c8-4cfb255fae69.png)

**[3]:  Getting the signal name when you want to connect.:-**

![image](https://user-images.githubusercontent.com/98526116/210027003-19565567-5298-469e-b90c-1531dc00b736.png)

**[4]:  Getting node path when you call get node.:-**

![image](https://user-images.githubusercontent.com/98526116/210027149-9157eed8-12b5-4583-925d-62e00b690696.png)

===

These are the missing features in the current rider extension for Godot.

**Comment by Perndoe** [comment]
ok

**Comment by Intrivus** [comment]
I think this is incredibly necessary

**Comment by jsbeckr** [comment]
https://github.com/JetBrains/godot-support/assets/147412/86090771-ba5f-492c-9821-733c09efc5bd

Not yet perfect but it's a beginning 😁

**Comment by van800** [comment]
@jsbeckr I have recognized, some of your commits are from different email. I'd try to fix that and force push.
