### ISSUE TITLE
[Question] How to run/debug individual scene?

### ISSUE THREAD

**Issue by cdfq152313** [JetBrains/godot-support#89]
Readme page shows following text.

> Context menu on a scene file allows running game directly to that scene.

However, when I right click scene(.tscn) file, there are no any run/debug action.
How can I fix it?

**Comment by van800** [comment]
Make sure that scenes are added in the csproj.

  ```
  <ItemGroup>
    <None Include="**/*.tscn" />
  </ItemGroup>
  ```

**Comment by cdfq152313** [comment]
It works!!! Thank you!!!
