### ISSUE TITLE
"Start and Debug" button doesn't work properly at first startup of Rider

### ISSUE THREAD

**Issue by Meister1593** [JetBrains/godot-support#9]
This bug appears only first time i run Godot with Rider on system and only on first launch through this button.
Basically i run game through this button, it closes and debugger attaches to nothing (not sure to what because debugger should stop if nothing is attached)

Steps to reproduce:
1. Reboot, only on fresh system that works (probably related to caches)
2. Launch Godot project and Rider as usual.
3. Try to launch game through "Start and Debug".

[Attached video](https://drive.google.com/file/d/1DlZoSOvZ0Xrjjel3FmqP8bzpkK8OqpZ8/view?usp=sharing)
 Using Godot 3.2.1 (Mono), Godot Support 2020.1.3 and Rider 2020.1 EAP 7 on Arch Linux

**Comment by Meister1593** [comment]
Also found that running old way (through Listen(1) and Run with attach(2) reproduces this bug too.
1. Run old way
2. Run with new button
3. Bug as in video above appears.

**Comment by van800** [comment]
@Meister1593 Fix is available in branch https://github.com/JetBrains/godot-support/tree/run_and_debug_2
Would you mind trying it before I merge it and deploy the update?

**Comment by Meister1593** [comment]
Doesn't seem to be working for me at all now
[https://drive.google.com/file/d/1JVpACyDShHsPTo3x0DY5RILggKwNWSgx/view?usp=sharing](Video)

**Comment by Meister1593** [comment]
Haven't checked #9 before closing, but i can't it reproduce it now by doing same thing in previous comment, so i guess it's fixed too.

**Comment by van800** [comment]
Thank you! I have published the update.
