### ISSUE TITLE
[Godot 4] Filter out source generated classes in code navigation popups etc.

### ISSUE THREAD

**Issue by Flavelius** [JetBrains/godot-support#92]
In godot 4, a lot of work is lifted to source generators which in turn generate a lot of connected classes that rider then picks up for example in code navigation popups. This is a lot of unnecessary visual noise that should likely be filtered out as it's not relevant to user code.
Example:
![grafik](https://user-images.githubusercontent.com/8841352/215269087-e0651121-866f-439b-9ad1-955f066eac65.png)

**Comment by van800** [comment]
Thank you for the request.
Related to https://youtrack.jetbrains.com/issue/RIDER-85189/Navigation-clean-up-unity-source-generators-from-navigation

**Comment by van800** [comment]
A note for me or anyone who'd want to implement this

1. Use similar approach as here:
https://github.com/JetBrains/resharper-unity/commits/net231/resharper/resharper-unity/src/Unity/CSharp/Psi/Search/UnityDotsSearchFactory.cs

2. Add a separate action for opening generated code, if needed, similar to:
https://github.com/JetBrains/resharper-unity/blob/net231/resharper/resharper-unity/src/Unity/CSharp/Feature/Services/Generate/Dots/OpenDotsSourceGeneratedFileBulbAction.cs

**Comment by van800** [comment]
Most likely would be fixed with in [2023.3 in Rider itself](https://youtrack.jetbrains.com/issue/RIDER-85689/Ability-to-ignore-generated-documents-from-Go-to-Declaration-or-Usages), no need for a special fix in the plugin.

**Comment by Diu** [comment]
I tried to use a modified UnityDotsSearchFactory and was able to hide the found declarations. 
Sadly it still shows the found usages, the documentation is rather lacking, and I have no clue what I am doing.

**Comment by van800** [comment]
What do you want to hide from navigation except of the generated declaration of all partial classed derived from the GodotObject?

**Comment by van800** [comment]
finally fixed by the ReSharper platform https://youtrack.jetbrains.com/issue/RIDER-85689/Ability-to-ignore-generated-documents-from-Go-to-Declaration-or-Usages
